ifeq ($(UNAME), Windows)
  BINARY_PLATFORM_DIRECTORY := binary/windows
  OUTPUT_FILE := $(BINARY_PLATFORM_DIRECTORY)/CTemplate.exe
else ifeq ($(UNAME), Linux)
  BINARY_PLATFORM_DIRECTORY := binary/linux
  OUTPUT_FILE := $(BINARY_PLATFORM_DIRECTORY)/CTemplate.out
endif

PROGRAM_SOURCE_DIRECTORY := program/source
PROGRAM_INCLUDE_DIRECTORY := program/include
BINARY_DIRECTORY := binary
BINARY_OBJECT_DIRECTORY := binary/object
CC_SOURCE_FILES := $(wildcard $(PROGRAM_SOURCE_DIRECTORY)/*.c)
H_SOURCE_FILES := $(wildcard $(PROGRAM_INCLUDE_DIRECTORY)/*.h)
OBJECT_FILES := $(patsubst $(PROGRAM_SOURCE_DIRECTORY)/%.c, $(BINARY_OBJECT_DIRECTORY)/%.o, $(CC_SOURCE_FILES))
DEPENDENCY_FILES := $(patsubst $(BINARY_OBJECT_DIRECTORY)/%.o, $(BINARY_OBJECT_DIRECTORY)/%.d, $(OBJECT_FILES))
